2020-02-25 20:12:41,220 ERROR: Exception on /explore [GET] [in /Library/Python/3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/main/routes.py", line 64, in explore
    prev_url=prev_url)
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Library/Python/3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/index.html", line 19, in block "content"
    {% include '_post.html' %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/Library/Python/3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Python/3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Library/Python/3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2020-02-25 20:18:42,601 ERROR: Exception on /user/nessig12 [GET] [in /Library/Python/3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Python/3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/main/routes.py", line 79, in user
    next_url=next_url, prev_url=prev_url)
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Library/Python/3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/base.html", line 49, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/user.html", line 15, in block "app_content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "/Library/Python/3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Python/3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Library/Python/3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'main.edit_profile' instead?
2020-02-25 20:21:08,918 INFO: Microblog startup [in /Users/normandieessig/Desktop/Thesis/Practice/app/__init__.py:74]
