2020-02-24 11:24:11,305 ERROR: Exception on /auth/login [GET] [in /Library/Python/3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Library/Python/3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/auth/login.html", line 12, in block "app_content"
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
  File "/Library/Python/3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Python/3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Library/Python/3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
2020-02-24 11:24:12,712 ERROR: Exception on /auth/login [GET] [in /Library/Python/3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/auth/routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Library/Python/3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Library/Python/3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Library/Python/3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/auth/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 11, in block "html"
    {%- endblock metas %}
  File "/Users/normandieessig/Library/Python/3.7/lib/python/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 13, in block "body"
    {%- block styles %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/normandieessig/Desktop/Thesis/Practice/app/templates/auth/login.html", line 12, in block "app_content"
    <p>New User? <a href="{{ url_for('register') }}">Click to Register!</a></p>
  File "/Library/Python/3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Python/3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Library/Python/3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'register'. Did you mean 'auth.register' instead?
2020-02-24 11:25:20,891 INFO: Microblog startup [in /Users/normandieessig/Desktop/Thesis/Practice/app/__init__.py:74]
2020-02-24 11:27:57,395 INFO: Microblog startup [in /Users/normandieessig/Desktop/Thesis/Practice/app/__init__.py:74]
2020-02-24 11:30:20,638 INFO: Microblog startup [in /Users/normandieessig/Desktop/Thesis/Practice/app/__init__.py:74]
